k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: arn:aws:eks:us-east-1:492807964465:cluster/monitoring-dev
  currentCluster: arn:aws:eks:us-east-1:492807964465:cluster/monitoring-dev
  clusters:
    arn:aws:eks:us-east-1:492807964465:cluster/monitoring-dev:
      namespace:
        active: loki
        lockFavorites: false
        favorites:
        - loki
        - cert-manager
        - all
        - default
      view:
        active: node
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-jeffrey
